# Generated by Django 6.1.1 on 2026-09-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_hall_meta_description_hall_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
