# Generated by Django 6.1.1 on 2026-09-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0007_hall_slug_poster_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='URL'),
        ),
    ]
